### ISSUE TITLE
Cache improvements

### ISSUE THREAD

**Issue by MolotovCherry** [nttld/setup-ndk#220]
Even right now although it adds it to the cache, it still has to download the whole NDK and can take about 2 minutes per run just downloading and extracting.

If the [official cache action](https://github.com/actions/cache) is supported, then we could use it before it before the setup-ndk action, and all this action would have to do is provide an input which indicates whether there was a cache hit or not, and add it to the PATH (rather than having to download and extract it all again). However, I believe some changes to where the NDK gets downloaded to might be required for the official cache action to cache it (not 100% sure about this) since the official cache action needs to know where to cache from, and this setup-ndk action currently extracts to a random identifier in the runner temp folder, so the official cache action doesn't really know *where* it is (also, I think the official cache action can only cache from the workspace directory, not completely sure though).

But other than that, supporting a run like this could cut times from about 2 minutes to 20 seconds.

An example API could be similar to this:
```yaml
  - uses: actions/cache@v2
    id: cache
    with:
      path: ndk
      key: ndk

  - uses: nttld/setup-ndk@v1
    id: setup-ndk
    with:
      ndk-version: r22b
      add-to-path: true
      directory: ndk #this is local to workspace root
      cache-hit: ${{ steps.cache.outputs.cache-hit }} # true or false
```
If `cache-hit` is true, then setup-ndk will only need to `add-to-path`, and can skip downloading, extracting, and add to tool cache steps.
