### ISSUE TITLE
Error about missing file/directory when trying to use

### ISSUE THREAD

**Issue by achou11** [nttld/setup-ndk#508]
Entirely possible that there's something wrong that I'm doing (not very proficient with GH Actions 😅), but hoping to get some clues about how to address the issue I'm running into...

I'm getting this error when trying to run this action:

```sh
Error: ENOENT: no such file or directory, lstat '/opt/hostedtoolcache/ndk/r24/x64/*'
```

Here's the relevant configuration:

```yml
steps:
  - uses: actions/checkout@v4

  - name: Setup NDK
    uses: nttld/setup-ndk@v1
    id: setup_ndk
    with:
      ndk-version: r24 # https://github.com/android/ndk/wiki/Unsupported-Downloads#r24
      local-cache: true
```

Additional context:

- The workflow runs on `ubuntu-latest`
- The workflow uses a `matrix` configuration
