### ISSUE TITLE
`local-cache` not work because of broken symlink

### ISSUE THREAD

**Issue by fumiama** [nttld/setup-ndk#547]
### My YAML
```yaml
name: test
on: [ push, pull_request ]

jobs:
  test_ubuntu:
    name: Run Make Test on Ubuntu 🧪
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          local-cache: true

      - name: Setup Go Environment
        uses: actions/setup-go@master

      - name: Test Build
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          BUILD_MACHINE: linux
        run: |
          echo NDK path is $NDK_HOME
          ls -hl $NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
          ls -hl /opt/hostedtoolcache
          $NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang --version
          make -e
```
### The output
- It is clear that the cache restored successfully.

  ![ndk](https://github.com/nttld/setup-ndk/assets/41315874/94407e6f-14cc-42ee-a686-342911c5778a)

- But the symlink to `/opt/hostedtoolcache` is broken.

  ![build](https://github.com/nttld/setup-ndk/assets/41315874/2df7376c-66b4-44d5-8519-1b7d363b68b2)
